# Generated by Django 5.1.3 on 2024-11-19 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type1', models.CharField(max_length=20)),
                ('type2', models.CharField(blank=True, max_length=20, null=True)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('gender_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('egg_groups', models.CharField(blank=True, max_length=100, null=True)),
                ('abilities', models.CharField(max_length=200)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('sp_attack', models.IntegerField()),
                ('sp_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('image_url', models.URLField()),
                ('evolution_level', models.IntegerField(blank=True, null=True)),
                ('evolution_method', models.CharField(blank=True, max_length=100, null=True)),
                ('evolves_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_evolves_to', to='pokemon.pokemon')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
