# Generated by Django 5.1.3 on 2024-11-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
