# Generated by Django 5.1.3 on 2024-12-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolution_level',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='dex_entry',
            field=models.TextField(default='pokemons dae'),
        ),
    ]
