# Generated by Django 5.1.3 on 2024-12-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_alter_pokemon_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='image_url',
        ),
    ]
