# Generated by Django 5.1.3 on 2024-12-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='csvid',
            field=models.IntegerField(default=-1),
        ),
    ]
